version: '3.8'
services:
  myapp:
    container_name: myapp
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports: [ "8000:8000" ]
    depends_on:
      myapp_db:
        condition: service_healthy
    volumes:
      - ./:/app

  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - myapp

  myapp_db:
    container_name: myapp_db
    image: postgres:14-alpine
    ports: [ "5432:5432" ]
    volumes:
      - myapp_db:/var/lib/postgresql/data
    stop_signal: SIGINT # Fast shutdown.
    environment:
      - POSTGRES_PASSWORD=5ZP3Z9WW&92P#ZAp
    healthcheck:
      test:
        - "CMD-SHELL"
        - "pg_isready -h localhost -p 5432 -U postgres"
      timeout: 30s
      interval: 5s

volumes:
  myapp_db:
