version: '3.8'
services:
  nasa_app:
    container_name: nasa_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - db_network
      - web_network
    ports: [ 8000:8000 ]
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app

  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - nasa_app

  db:
    image: postgres:14-alpine
    ports: [ 5432:5432 ]
    volumes:
      - db:/var/lib/postgresql/data
    stop_signal: SIGINT # Fast shutdown.
    environment: [ POSTGRES_HOST_AUTH_METHOD=trust ]
    networks:
      - db_network
    healthcheck:
      test:
        - "CMD-SHELL"
        - "pg_isready -h localhost -p 5432 -U postgres"
      timeout: 30s
      interval: 5s

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge

volumes:
  db:
 